In [16]:
#Logistic Regression
#雖然名為迴歸，但常用於分類（二元或多類別）
from sklearn import preprocessing, linear_model
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection  import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.rcParams['font.family']='SimHei' #黑體

In [17]:
data_path = '../data/'
df_train = pd.read_csv(data_path + 'titanic_train.csv') #鐵達尼
df3=df_train[['Sex','Pclass','Age','Survived']] #用'Sex','Pclass','Age' 三個變數預測'Survived'(存活率)
df3.head()

      Sex  Pclass   Age  Survived
0    male       3  22.0         0
1  female       1  38.0         1
2  female       3  26.0         1
3  female       1  35.0         1
4    male       3  35.0         0

In [18]:
# 創造 dummy variables   將SEX轉換成 0，1
label_encoder = preprocessing.LabelEncoder()
encoded_Sex = label_encoder.fit_transform(df3["Sex"])
df3["Sex"]=encoded_Sex
df3.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

   Sex  Pclass   Age  Survived
0    1       3  22.0         0
1    0       1  38.0         1
2    0       3  26.0         1
3    0       1  35.0         1
4    1       3  35.0         0

In [19]:
df3 = df3.fillna(df3.mean())

In [20]:
#切分訓練 測試資料
x=df3[['Sex','Pclass','Age']]
y=df3[['Survived']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=20170816) #random_state 種子值

x_train

     Sex  Pclass        Age
79     0       3  30.000000
838    1       3  32.000000
728    1       2  25.000000
116    1       3  70.500000
413    1       2  29.699118
572    1       1  36.000000
556    0       1  48.000000
618    0       2   4.000000
472    0       2  33.000000
171    1       3   4.000000
419    0       3  10.000000
752    1       3  33.000000
622    1       3  20.000000
25     0       3  38.000000
230    0       1  35.000000
846    1       3  29.699118
87     1       3  29.699118
796    0       1  49.000000
737    1       1  35.000000
30     1       1  40.000000
875    0       3  15.000000
552    1       3  29.699118
365    1       3  30.000000
775    1       3  18.000000
174    1       1  56.000000
491    1       3  21.000000
756    1       3  28.000000
633    1       1  29.699118
143    1       3  19.000000
308    1       2  30.000000
..   ...     ...        ...
319    0       1  40.000000
384    1       3  29.699118
431    0       3  29.699118
62     1       1  45.000000
844    1       3  17.000000
505    1       1  18.000000
91     1       3  20.000000
683    1       3  14.000000
571    0       1  53.000000
681    1       1  27.000000
709    1       3  29.699118
774    0       2  54.000000
16     1       3   2.000000
841    1       2  16.000000
881    1       3  33.000000
515    1       1  47.000000
540    0       1  36.000000
257    0       1  30.000000
661    1       3  40.000000
244    1       3  30.000000
28     0       3  29.699118
561    1       3  40.000000
289    0       3  22.000000
654    0       3  18.000000
398    1       2  23.000000
459    1       3  29.699118
299    0       1  50.000000
549    1       2   8.000000
328    0       3  31.000000
13     1       3  39.000000

[623 rows x 3 columns]

In [21]:
#標準化 :為了避免偏向某個變數去做訓練
from sklearn.preprocessing  import StandardScaler
sc=StandardScaler()

sc.fit(x_train)

x_train_nor=sc.transform(x_train)
x_test_nor=sc.transform(x_test)
print(x_train_nor)
print(x_test_nor)

[[-1.39236462  0.79275638  0.01991476]
 [ 0.71820268  0.79275638  0.17578982]
 [ 0.71820268 -0.40599902 -0.36977287]
 ...
 [ 0.71820268 -0.40599902 -1.69471084]
 [-1.39236462  0.79275638  0.09785229]
 [ 0.71820268  0.79275638  0.72135251]]
[[ 0.71820268 -1.60475443  0.56547746]
 [ 0.71820268 -0.40599902  0.09785229]
 [-1.39236462 -0.40599902  1.57866532]
 [ 0.71820268 -1.60475443 -0.13596029]
 [-1.39236462  0.79275638 -0.21389782]
 [-1.39236462 -0.40599902 -2.08439848]
 [ 0.71820268  0.79275638 -0.00353526]
 [-1.39236462 -1.60475443 -0.83739804]
 [ 0.71820268 -1.60475443  1.11104015]
 [ 0.71820268 -1.60475443  0.56547746]
 [-1.39236462  0.79275638 -1.07121062]
 [-1.39236462  0.79275638 -0.52564793]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638 -0.83739804]
 [-1.39236462  0.79275638  0.87722757]
 [ 0.71820268 -0.40599902  1.57866532]
 [-1.39236462 -0.40599902  0.48753993]
 [ 0.71820268 -1.60475443  1.26691521]
 [ 0.71820268  0.79275638 -0.29183535]
 [ 0.71820268 -1.60475443  0.01991476]
 [ 0.71820268  0.79275638 -0.00353526]
 [-1.39236462 -1.60475443 -0.00353526]
 [ 0.71820268 -0.40599902 -0.83739804]
 [ 0.71820268  0.79275638 -0.48667917]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268 -1.60475443  1.96835296]
 [ 0.71820268  0.79275638  0.4096024 ]
 [ 0.71820268 -1.60475443  1.73454037]
 [-1.39236462 -0.40599902  0.9551651 ]
 [ 0.71820268 -1.60475443  1.42279026]
 [ 0.71820268  0.79275638  0.25372735]
 [ 0.71820268 -1.60475443 -0.13596029]
 [-1.39236462  0.79275638 -0.4477104 ]
 [ 0.71820268  0.79275638  0.33166487]
 [ 0.71820268  0.79275638 -1.14914815]
 [-1.39236462 -0.40599902  0.21475858]
 [ 0.71820268  0.79275638  0.01991476]
 [ 0.71820268 -1.60475443 -0.00353526]
 [-1.39236462 -1.60475443  0.4096024 ]
 [ 0.71820268  0.79275638 -0.13596029]
 [-1.39236462 -1.60475443 -0.4477104 ]
 [-1.39236462 -1.60475443  0.72135251]
 [-1.39236462 -1.60475443 -0.00353526]
 [ 0.71820268  0.79275638 -0.52564793]
 [ 0.71820268  0.79275638 -0.4477104 ]
 [-1.39236462 -1.60475443  1.18897768]
 [-1.39236462  0.79275638 -0.4477104 ]
 [ 0.71820268 -0.40599902  3.13741587]
 [-1.39236462 -1.60475443 -0.52564793]
 [ 0.71820268 -1.60475443  2.35804059]
 [-1.39236462 -0.40599902 -0.13596029]
 [-1.39236462  0.79275638 -0.60358546]
 [ 0.71820268 -0.40599902 -0.91533557]
 [ 0.71820268  0.79275638 -0.13596029]
 [-1.39236462 -0.40599902  0.48753993]
 [ 0.71820268  0.79275638 -0.60358546]
 [ 0.71820268  0.79275638 -0.36977287]
 [-1.39236462 -0.40599902 -0.4477104 ]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268 -1.60475443  0.48753993]
 [-1.39236462  0.79275638 -0.00353526]
 [ 0.71820268 -1.60475443  0.72135251]
 [-1.39236462  0.79275638 -0.00353526]
 [-1.39236462 -1.60475443 -0.68152298]
 [ 0.71820268  0.79275638  0.48753993]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638 -0.4477104 ]
 [ 0.71820268 -1.60475443  0.64341499]
 [-1.39236462 -1.60475443 -0.60358546]
 [-1.39236462 -0.40599902 -0.60358546]
 [-1.39236462 -0.40599902 -0.13596029]
 [ 0.71820268  0.79275638  0.4096024 ]
 [ 0.71820268  0.79275638 -2.00646095]
 [-1.39236462 -0.40599902 -0.4477104 ]
 [ 0.71820268 -1.60475443  2.43597812]
 [ 0.71820268  0.79275638  0.25372735]
 [-1.39236462  0.79275638 -0.29183535]
 [-1.39236462 -0.40599902  0.33166487]
 [ 0.71820268 -1.60475443  2.51391565]
 [-1.39236462 -0.40599902  0.79929004]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638 -0.75946051]
 [ 0.71820268 -1.60475443  0.09785229]
 [ 0.71820268 -1.60475443 -0.13596029]
 [ 0.71820268  0.79275638 -0.29183535]
 [ 0.71820268 -1.60475443  1.22794644]
 [-1.39236462 -0.40599902 -0.00353526]
 [ 0.71820268 -0.40599902 -0.00353526]
 [ 0.71820268  0.79275638  0.48753993]
 [ 0.71820268 -0.40599902 -0.05802276]
 [ 0.71820268 -0.40599902 -0.05802276]
 [ 0.71820268  0.79275638 -0.60358546]
 [-1.39236462 -1.60475443 -2.16233601]
 [-1.39236462 -0.40599902 -2.00646095]
 [-1.39236462  0.79275638 -0.00353526]
 [ 0.71820268 -1.60475443  1.57866532]
 [ 0.71820268 -0.40599902  2.28010307]
 [ 0.71820268  0.79275638 -2.00646095]
 [-1.39236462 -0.40599902  0.33166487]
 [-1.39236462 -1.60475443 -0.00353526]
 [ 0.71820268  0.79275638 -1.61677332]
 [ 0.71820268  0.79275638 -1.38296073]
 [-1.39236462  0.79275638 -2.16233601]
 [ 0.71820268 -1.60475443 -0.00353526]
 [-1.39236462  0.79275638 -1.61677332]
 [ 0.71820268  0.79275638  0.17578982]
 [ 0.71820268 -0.40599902  0.25372735]
 [-1.39236462 -1.60475443 -0.00353526]
 [ 0.71820268 -0.40599902  0.01991476]
 [ 0.71820268 -1.60475443  1.89041543]
 [ 0.71820268 -1.60475443  3.13741587]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268 -0.40599902 -2.16233601]
 [ 0.71820268  0.79275638 -2.08439848]
 [ 0.71820268  0.79275638 -0.00353526]
 [-1.39236462 -0.40599902  0.01991476]
 [-1.39236462 -1.60475443  0.01991476]
 [ 0.71820268  0.79275638 -0.75946051]
 [-1.39236462 -0.40599902  1.57866532]
 [ 0.71820268  0.79275638 -1.53883579]
 [ 0.71820268  0.79275638 -1.22708568]
 [-1.39236462  0.79275638  0.09785229]
 [-1.39236462  0.79275638 -0.9932731 ]
 [-1.39236462 -0.40599902 -0.00353526]
 [ 0.71820268  0.79275638 -0.00353526]
 [-1.39236462  0.79275638 -0.60358546]
 [-1.39236462 -1.60475443 -1.07121062]
 [ 0.71820268  0.79275638 -1.07121062]
 [ 0.71820268 -0.40599902  1.89041543]
 [-1.39236462 -1.60475443 -0.60358546]
 [ 0.71820268  0.79275638 -0.29183535]
 [ 0.71820268 -1.60475443 -0.00353526]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638  0.33166487]
 [-1.39236462  0.79275638 -2.00646095]
 [-1.39236462  0.79275638 -1.92852343]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638 -0.91533557]
 [-1.39236462 -0.40599902 -1.69471084]
 [ 0.71820268  0.79275638 -0.60358546]
 [-1.39236462 -1.60475443 -1.22708568]
 [ 0.71820268 -0.40599902  2.35804059]
 [-1.39236462  0.79275638 -0.00353526]
 [ 0.71820268 -0.40599902 -2.24027354]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638 -1.07121062]
 [ 0.71820268 -0.40599902  2.51391565]
 [ 0.71820268 -1.60475443  3.2153534 ]
 [ 0.71820268  0.79275638  0.64341499]
 [-1.39236462 -1.60475443  0.4096024 ]
 [ 0.71820268  0.79275638 -0.00353526]
 [-1.39236462  0.79275638 -0.60358546]
 [-1.39236462 -1.60475443  0.9551651 ]
 [-1.39236462  0.79275638 -0.00353526]
 [ 0.71820268 -0.40599902 -2.25352292]
 [ 0.71820268  0.79275638 -0.00353526]
 [-1.39236462  0.79275638  0.05888353]
 [ 0.71820268 -0.40599902 -0.13596029]
 [ 0.71820268 -0.40599902  0.01991476]
 [-1.39236462 -0.40599902  0.79929004]
 [-1.39236462 -0.40599902  1.18897768]
 [ 0.71820268  0.79275638  0.17578982]
 [-1.39236462 -0.40599902  1.96835296]
 [-1.39236462 -1.60475443 -0.68152298]
 [ 0.71820268 -1.60475443 -0.36977287]
 [-1.39236462 -1.60475443 -0.00353526]
 [-1.39236462  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638  0.17578982]
 [ 0.71820268  0.79275638  0.17578982]
 [ 0.71820268 -0.40599902  1.42279026]
 [ 0.71820268 -0.40599902  0.33166487]
 [-1.39236462 -1.60475443  1.42279026]
 [ 0.71820268 -0.40599902 -0.91533557]
 [-1.39236462  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268 -1.60475443 -0.21389782]
 [ 0.71820268  0.79275638  0.72135251]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268 -0.40599902 -0.4477104 ]
 [ 0.71820268  0.79275638 -0.13596029]
 [ 0.71820268 -1.60475443 -0.00353526]
 [ 0.71820268  0.79275638 -1.07121062]
 [-1.39236462  0.79275638 -0.13596029]
 [-1.39236462 -1.60475443  2.20216554]
 [ 0.71820268 -0.40599902  1.73454037]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638 -0.00353526]
 [-1.39236462 -1.60475443 -0.05802276]
 [ 0.71820268 -1.60475443  1.18897768]
 [ 0.71820268 -1.60475443  0.9551651 ]
 [-1.39236462 -0.40599902 -0.4477104 ]
 [ 0.71820268 -0.40599902  1.34485273]
 [ 0.71820268  0.79275638 -2.24027354]
 [ 0.71820268 -1.60475443  2.04629048]
 [ 0.71820268 -0.40599902  0.09785229]
 [-1.39236462  0.79275638 -0.4477104 ]
 [-1.39236462  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638 -1.07121062]
 [ 0.71820268  0.79275638  0.25372735]
 [-1.39236462 -1.60475443  2.20216554]
 [-1.39236462 -0.40599902 -0.91533557]
 [ 0.71820268  0.79275638  0.17578982]
 [ 0.71820268  0.79275638 -0.36977287]
 [-1.39236462 -1.60475443 -0.60358546]
 [ 0.71820268  0.79275638  0.48753993]
 [-1.39236462  0.79275638 -0.00353526]
 [-1.39236462  0.79275638 -0.4477104 ]
 [-1.39236462  0.79275638 -0.00353526]
 [-1.39236462  0.79275638 -2.25975792]
 [ 0.71820268 -1.60475443 -0.00353526]
 [-1.39236462  0.79275638 -1.22708568]
 [ 0.71820268 -0.40599902  0.17578982]
 [ 0.71820268  0.79275638 -0.36977287]
 [ 0.71820268  0.79275638 -0.75946051]
 [ 0.71820268  0.79275638  0.17578982]
 [ 0.71820268  0.79275638 -0.00353526]
 [-1.39236462  0.79275638 -0.68152298]
 [-1.39236462  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638  0.01991476]
 [ 0.71820268  0.79275638  0.09785229]
 [ 0.71820268  0.79275638  0.87722757]
 [ 0.71820268 -0.40599902 -0.36977287]
 [ 0.71820268 -1.60475443  1.50072779]
 [-1.39236462  0.79275638 -0.91533557]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268 -1.60475443  0.4096024 ]
 [ 0.71820268  0.79275638 -1.07121062]
 [ 0.71820268 -0.40599902  0.09785229]
 [-1.39236462 -0.40599902  2.12422801]
 [-1.39236462 -1.60475443  0.87722757]
 [-1.39236462 -1.60475443 -0.4477104 ]
 [ 0.71820268 -1.60475443  1.34485273]
 [-1.39236462 -0.40599902 -0.60358546]
 [ 0.71820268 -0.40599902 -0.00353526]
 [ 0.71820268  0.79275638 -0.75946051]
 [-1.39236462 -0.40599902  1.57866532]
 [-1.39236462 -1.60475443  0.09785229]
 [ 0.71820268 -0.40599902  0.21475858]
 [-1.39236462 -1.60475443  2.35804059]
 [-1.39236462 -0.40599902 -0.05802276]
 [ 0.71820268  0.79275638 -0.13596029]
 [ 0.71820268  0.79275638 -1.07121062]
 [-1.39236462  0.79275638 -0.75946051]
 [-1.39236462  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638  1.65660284]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638 -0.91533557]
 [ 0.71820268 -1.60475443  0.33166487]
 [ 0.71820268 -0.40599902 -1.07121062]
 [ 0.71820268  0.79275638 -0.13596029]
 [-1.39236462  0.79275638 -1.14914815]
 [ 0.71820268 -0.40599902  0.01991476]
 [ 0.71820268 -1.60475443 -2.00646095]
 [ 0.71820268 -0.40599902 -2.26599292]
 [-1.39236462  0.79275638  1.18897768]
 [ 0.71820268  0.79275638 -0.68152298]
 [-1.39236462 -0.40599902 -1.8505859 ]
 [ 0.71820268  0.79275638 -0.00353526]
 [ 0.71820268  0.79275638 -0.75946051]
 [ 0.71820268  0.79275638 -0.75946051]
 [ 0.71820268  0.79275638 -0.4477104 ]
 [-1.39236462  0.79275638 -1.22708568]
 [-1.39236462 -0.40599902  0.79929004]
 [ 0.71820268 -1.60475443 -0.00353526]
 [ 0.71820268  0.79275638 -0.4477104 ]
 [-1.39236462  0.79275638 -0.00353526]
 [ 0.71820268 -0.40599902 -0.68152298]]

In [22]:
#訓練資料分類效果(3個參數)
from sklearn.linear_model  import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train_nor,y_train)
#'Sex','Pclass','Age'
# 印出係數
print(lr.coef_)
# 印出截距
print(lr.intercept_ )

#output:

#係數: [[-1.30778904 -1.19424825 -0.64119698]]
#截距: [-0.5100545]
#

[[-1.19920441 -1.00016465 -0.34276744]]
[-0.79653825]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [23]:
#機率分類判斷
import numpy as np
test_result=np.round(lr.predict_proba(x_test_nor),3)

In [31]:
test_result.max()

0.962

In [35]:
#評估分類模型的好壞--用混淆矩陣

from sklearn.metrics import confusion_matrix

cnf=confusion_matrix(y_test,lr.predict(x_test_nor))
print('混淆矩陣: ',cnf)


#import itertools
#target_name=['yes','no'] #是否生存 
#plot_confusion_matrix(cnf,classes=target_name,title='混淆矩陣')
#plt.show()
#因此，此邏吉斯回規模型的準確率為:

#Accuracy:  13+84/13+84+19+34 =0.64 (79%的準確率)

混淆矩陣:  [[131  19]
 [ 34  84]]

In [33]:

#PS: 要使用視覺化混淆矩陣要先執行以下的code (官網提供的)

#plot confusion matrix 官網提供
import numpy as np
import matplotlib.pyplot as plt
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')